extensions:
  health_check:
    endpoint: 0.0.0.0:13133

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 384
    spike_limit_mib: 96

  resource/lab:
    attributes:
      - key: deployment.environment.name
        value: lab
        action: upsert

  resourcedetection:
    detectors: [system]
    override: false
    timeout: 2s

  # tail_sampling:
  #   decision_wait: 5s
  #   num_traces: 5000
  #   expected_new_traces_per_sec: 100
  #   policies:
  #     - name: keep-errors
  #       type: status_code
  #       status_code:
  #         status_codes: [ERROR]
  #     - name: keep-slow-traces
  #       type: latency
  #       latency:
  #         threshold_ms: 1000
  #     - name: sample-normal-traffic
  #       type: probabilistic
  #       probabilistic:
  #         sampling_percentage: 100 # 25 for production

  batch:
    timeout: 1s
    send_batch_size: 512

exporters:
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true

  elasticsearch/otel:
    endpoints: [http://elasticsearch:9200]
    mapping:
      mode: otel

  debug:
    verbosity: basic

service:
  extensions: [health_check]
  telemetry:
    logs:
      level: info
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, resource/lab, resourcedetection, batch]
      exporters: [otlp/jaeger, debug]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, resource/lab, resourcedetection, batch]
      exporters: [elasticsearch/otel, debug]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, resource/lab, resourcedetection, batch]
      exporters: [elasticsearch/otel, debug]
