namespace Catalog.API.Application.Movies.Commands.CreateMovie;

public class CreateMovieCommandHandler : IRequestHandler<CreateMovieCommand, int>
{
    private readonly CatalogContext _context;

    // Inject the CatalogContext through the constructor
    public CreateMovieCommandHandler(CatalogContext context)
    {
        _context = context;
    }

    public async Task<int> Handle(CreateMovieCommand request, CancellationToken cancellationToken)
    {


        // 1. Map the CreateMovieCommand to a Movie entity
        var movie = new Movie
        {
            // Id will be generated by the database
            Title = request.Tiltle,
            //Title = "Wrong title",
            Description = request.Description,
            DurationMinutes = request.DurationMinutes,
            // postgresql datetime type does not support timezone, so we need to convert it to UTC
            ReleaseDate = request.ReleaseDate,
            Director = request.Director,
            Cast = request.Cast,
            TrailerUrl = request.TrailerUrl,
            PosterUrl = request.PosterUrl
        };
        _context.Movies.Add(movie);
        await _context.SaveChangesAsync(cancellationToken);

        using var activity = ActivityExtensions.ActivitySource.StartActivity("catalog.movie.create");
        var orderId = Guid.NewGuid();
        activity?.SetTag("movie.Id", movie.Id);
        activity?.SetTag("movie.Title", movie.Title);
        activity?.SetTag("movie.Description", request.Description);

        return movie.Id;
    }
}