<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <!-- <Nullable>enable</Nullable> -->
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit.Analyzers" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="MassTransit.Quartz" />

    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />    
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="MassTransit.EntityFrameworkCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Booking.API/Booking.API.csproj" />
    <ProjectReference Include="../../src/Booking.Infrastructure/Booking.Infrastructure.csproj" />
    <ProjectReference Include="../../src/Catalog.API/Catalog.API.csproj" />
    <ProjectReference Include="../../src/SagaOrchestration/SagaOrchestration.csproj" />
    <ProjectReference Include="../../src/Seat.API/Seat.API.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="NUnit.Framework" />
  </ItemGroup>

</Project>
